name = "budget-balancer"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "budget-balancer-db"
database_id = "4221dd60-5497-49ef-bde5-ecc04145bef9"

